### ISSUE TITLE
Your filter only leaves comments. Is this how it should be?

### ISSUE THREAD

**Issue by SergeyMi37** [karivatj/doxygen-objectscript#2]
Or is there still a lot of work ahead?
![image](https://github.com/karivatj/doxygen-objectscript/assets/18187317/8e0b972c-cd0c-4737-8c64-92aa1cfa5011)

**Comment by karivatj** [comment]
Works as expected. Code is omitted from the method bodies, and comments are kept as-is. If you're wondering why the code is not present, the reason is that from a Doxygen perspective, the actual code is irrelevant for documentation generation. Only the comments impact the documentation.

See: https://www.doxygen.nl/manual/docblocks.html#cppblock for more information.

"For methods and functions there is also a third type of description, the so called in body description, which consists of the concatenation of all comment blocks found within the body of the method or function."

- Kari

**Comment by SergeyMi37** [comment]
It's funny.)
